### ISSUE TITLE
range_measurements support

### ISSUE THREAD

**Issue by khulan3** [saleae/logic2-examples#12]
Hi,

I have installed **pip install logic2-automation** Salaea package. However it does not contain package for range_measurements.
I get error ModuleNotFoundError: No module named 'saleae.range_measurements'

Where do I get from saleae.range_measurements import DigitalMeasurer APIs.

Thanks and Best
Khulan

**Comment by timreyes** [comment]
It looks like Ryan was able to reply to you via the forum post below:
https://discuss.saleae.com/t/range-measurement-api-python/2528/2

I'll close this Issue Post for now, but feel free to continue chatting with us via the forum post above in case you have any further questions.
